trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  VM_IP: '74.225.249.3'
  VM_USER: 'cherry'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build Project'

- task: DownloadSecureFile@1
  name: sshKey
  inputs:
    secureFile: 'vm-deploy-key' 

- script: |
    mkdir -p ~/.ssh
    cp $(sshKey.secureFilePath) ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh -o StrictHostKeyChecking=no $(VM_USER)@$(VM_IP) 'cd /var/www/your-app && git pull origin main && npm install && npm start'
  displayName: 'Deploy to Azure VM'
